### ISSUE TITLE
Use with Jetpack Compose?

### ISSUE THREAD

**Issue by t1u1** [ensody/ReactiveState-Kotlin#28]
Hi,

I would like to understand how to use this library with Jetpack Compose. IIUC, this library can be used to build Business Logic and ViewModels, and then `@Composables` can consume the state-flows with `.collectAsState()`.

Is that correct? If so, would `.collectAsState()` introduce too much additional overhead?

Alternatively, is it possible to create a class that implements both `State` and `StateFlow` to avoid code and memory duplication?

thanks!

**Comment by wkornewald** [comment]
Yes, you can just use `collectAsState()`. This is the official method to convert a `StateFlow`, so there shouldn't be any overhead worth discussing.
